DOCKER_NAME = "Extended Color Selector"
DOCKER_ID = "pykrita_extended_color_selector"
SYNC_INTERVAL_MS = 100
SETTINGS_DIALOG_SIZE = 500,300
GLOBAL_SETTINGS_DIALOG_SIZE = 500,300
MIN_WHEEL_SIZE = 100
MAX_WHEEL_SIZE = 400
