<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Extended Color Selector</text>
        <Action name="toggle_portable_color_selector">
            <icon></icon>
            <text>Toggle Portable Color Selector</text>
            <whatsThis></whatsThis>
            <toolTip>Toggle portable color selector at anywhere</toolTip>
            <iconText></iconText>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>